// source: message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.message.BulletState', null, global);
goog.exportSymbol('proto.message.ChangeDir', null, global);
goog.exportSymbol('proto.message.CreateBullet', null, global);
goog.exportSymbol('proto.message.DoDash', null, global);
goog.exportSymbol('proto.message.GameCount', null, global);
goog.exportSymbol('proto.message.GameInit', null, global);
goog.exportSymbol('proto.message.GameStart', null, global);
goog.exportSymbol('proto.message.GameState', null, global);
goog.exportSymbol('proto.message.HealPackState', null, global);
goog.exportSymbol('proto.message.MagicItemState', null, global);
goog.exportSymbol('proto.message.PlayerDeadState', null, global);
goog.exportSymbol('proto.message.PlayerState', null, global);
goog.exportSymbol('proto.message.Wrapper', null, global);
goog.exportSymbol('proto.message.Wrapper.MessagetypeCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.Wrapper = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.message.Wrapper.oneofGroups_);
};
goog.inherits(proto.message.Wrapper, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.Wrapper.displayName = 'proto.message.Wrapper';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.GameInit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.GameInit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.GameInit.displayName = 'proto.message.GameInit';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.ChangeDir = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.ChangeDir, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.ChangeDir.displayName = 'proto.message.ChangeDir';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.GameState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.message.GameState.repeatedFields_, null);
};
goog.inherits(proto.message.GameState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.GameState.displayName = 'proto.message.GameState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.PlayerState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.PlayerState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.PlayerState.displayName = 'proto.message.PlayerState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.CreateBullet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.CreateBullet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.CreateBullet.displayName = 'proto.message.CreateBullet';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.BulletState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.BulletState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.BulletState.displayName = 'proto.message.BulletState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.GameCount = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.GameCount, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.GameCount.displayName = 'proto.message.GameCount';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.DoDash = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.DoDash, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.DoDash.displayName = 'proto.message.DoDash';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.GameStart = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.GameStart, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.GameStart.displayName = 'proto.message.GameStart';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.HealPackState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.HealPackState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.HealPackState.displayName = 'proto.message.HealPackState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.MagicItemState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.MagicItemState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.MagicItemState.displayName = 'proto.message.MagicItemState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.message.PlayerDeadState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.message.PlayerDeadState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.message.PlayerDeadState.displayName = 'proto.message.PlayerDeadState';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.message.Wrapper.oneofGroups_ = [[1,2,3,4,5,6,7]];

/**
 * @enum {number}
 */
proto.message.Wrapper.MessagetypeCase = {
  MESSAGETYPE_NOT_SET: 0,
  CHANGEDIR: 1,
  DODASH: 2,
  CREATEBULLET: 3,
  GAMESTATE: 4,
  GAMECOUNT: 5,
  GAMEINIT: 6,
  GAMESTART: 7
};

/**
 * @return {proto.message.Wrapper.MessagetypeCase}
 */
proto.message.Wrapper.prototype.getMessagetypeCase = function() {
  return /** @type {proto.message.Wrapper.MessagetypeCase} */(jspb.Message.computeOneofCase(this, proto.message.Wrapper.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.Wrapper.prototype.toObject = function(opt_includeInstance) {
  return proto.message.Wrapper.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.Wrapper} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.Wrapper.toObject = function(includeInstance, msg) {
  var f, obj = {
changedir: (f = msg.getChangedir()) && proto.message.ChangeDir.toObject(includeInstance, f),
dodash: (f = msg.getDodash()) && proto.message.DoDash.toObject(includeInstance, f),
createbullet: (f = msg.getCreatebullet()) && proto.message.CreateBullet.toObject(includeInstance, f),
gamestate: (f = msg.getGamestate()) && proto.message.GameState.toObject(includeInstance, f),
gamecount: (f = msg.getGamecount()) && proto.message.GameCount.toObject(includeInstance, f),
gameinit: (f = msg.getGameinit()) && proto.message.GameInit.toObject(includeInstance, f),
gamestart: (f = msg.getGamestart()) && proto.message.GameStart.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.Wrapper}
 */
proto.message.Wrapper.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.Wrapper;
  return proto.message.Wrapper.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.Wrapper} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.Wrapper}
 */
proto.message.Wrapper.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.message.ChangeDir;
      reader.readMessage(value,proto.message.ChangeDir.deserializeBinaryFromReader);
      msg.setChangedir(value);
      break;
    case 2:
      var value = new proto.message.DoDash;
      reader.readMessage(value,proto.message.DoDash.deserializeBinaryFromReader);
      msg.setDodash(value);
      break;
    case 3:
      var value = new proto.message.CreateBullet;
      reader.readMessage(value,proto.message.CreateBullet.deserializeBinaryFromReader);
      msg.setCreatebullet(value);
      break;
    case 4:
      var value = new proto.message.GameState;
      reader.readMessage(value,proto.message.GameState.deserializeBinaryFromReader);
      msg.setGamestate(value);
      break;
    case 5:
      var value = new proto.message.GameCount;
      reader.readMessage(value,proto.message.GameCount.deserializeBinaryFromReader);
      msg.setGamecount(value);
      break;
    case 6:
      var value = new proto.message.GameInit;
      reader.readMessage(value,proto.message.GameInit.deserializeBinaryFromReader);
      msg.setGameinit(value);
      break;
    case 7:
      var value = new proto.message.GameStart;
      reader.readMessage(value,proto.message.GameStart.deserializeBinaryFromReader);
      msg.setGamestart(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.Wrapper.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.Wrapper.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.Wrapper} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.Wrapper.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChangedir();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.message.ChangeDir.serializeBinaryToWriter
    );
  }
  f = message.getDodash();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.message.DoDash.serializeBinaryToWriter
    );
  }
  f = message.getCreatebullet();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.message.CreateBullet.serializeBinaryToWriter
    );
  }
  f = message.getGamestate();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.message.GameState.serializeBinaryToWriter
    );
  }
  f = message.getGamecount();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.message.GameCount.serializeBinaryToWriter
    );
  }
  f = message.getGameinit();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.message.GameInit.serializeBinaryToWriter
    );
  }
  f = message.getGamestart();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.message.GameStart.serializeBinaryToWriter
    );
  }
};


/**
 * optional ChangeDir changeDir = 1;
 * @return {?proto.message.ChangeDir}
 */
proto.message.Wrapper.prototype.getChangedir = function() {
  return /** @type{?proto.message.ChangeDir} */ (
    jspb.Message.getWrapperField(this, proto.message.ChangeDir, 1));
};


/**
 * @param {?proto.message.ChangeDir|undefined} value
 * @return {!proto.message.Wrapper} returns this
*/
proto.message.Wrapper.prototype.setChangedir = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.message.Wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.message.Wrapper} returns this
 */
proto.message.Wrapper.prototype.clearChangedir = function() {
  return this.setChangedir(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.message.Wrapper.prototype.hasChangedir = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional DoDash doDash = 2;
 * @return {?proto.message.DoDash}
 */
proto.message.Wrapper.prototype.getDodash = function() {
  return /** @type{?proto.message.DoDash} */ (
    jspb.Message.getWrapperField(this, proto.message.DoDash, 2));
};


/**
 * @param {?proto.message.DoDash|undefined} value
 * @return {!proto.message.Wrapper} returns this
*/
proto.message.Wrapper.prototype.setDodash = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.message.Wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.message.Wrapper} returns this
 */
proto.message.Wrapper.prototype.clearDodash = function() {
  return this.setDodash(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.message.Wrapper.prototype.hasDodash = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional CreateBullet createBullet = 3;
 * @return {?proto.message.CreateBullet}
 */
proto.message.Wrapper.prototype.getCreatebullet = function() {
  return /** @type{?proto.message.CreateBullet} */ (
    jspb.Message.getWrapperField(this, proto.message.CreateBullet, 3));
};


/**
 * @param {?proto.message.CreateBullet|undefined} value
 * @return {!proto.message.Wrapper} returns this
*/
proto.message.Wrapper.prototype.setCreatebullet = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.message.Wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.message.Wrapper} returns this
 */
proto.message.Wrapper.prototype.clearCreatebullet = function() {
  return this.setCreatebullet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.message.Wrapper.prototype.hasCreatebullet = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional GameState gameState = 4;
 * @return {?proto.message.GameState}
 */
proto.message.Wrapper.prototype.getGamestate = function() {
  return /** @type{?proto.message.GameState} */ (
    jspb.Message.getWrapperField(this, proto.message.GameState, 4));
};


/**
 * @param {?proto.message.GameState|undefined} value
 * @return {!proto.message.Wrapper} returns this
*/
proto.message.Wrapper.prototype.setGamestate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.message.Wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.message.Wrapper} returns this
 */
proto.message.Wrapper.prototype.clearGamestate = function() {
  return this.setGamestate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.message.Wrapper.prototype.hasGamestate = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional GameCount gameCount = 5;
 * @return {?proto.message.GameCount}
 */
proto.message.Wrapper.prototype.getGamecount = function() {
  return /** @type{?proto.message.GameCount} */ (
    jspb.Message.getWrapperField(this, proto.message.GameCount, 5));
};


/**
 * @param {?proto.message.GameCount|undefined} value
 * @return {!proto.message.Wrapper} returns this
*/
proto.message.Wrapper.prototype.setGamecount = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.message.Wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.message.Wrapper} returns this
 */
proto.message.Wrapper.prototype.clearGamecount = function() {
  return this.setGamecount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.message.Wrapper.prototype.hasGamecount = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional GameInit gameInit = 6;
 * @return {?proto.message.GameInit}
 */
proto.message.Wrapper.prototype.getGameinit = function() {
  return /** @type{?proto.message.GameInit} */ (
    jspb.Message.getWrapperField(this, proto.message.GameInit, 6));
};


/**
 * @param {?proto.message.GameInit|undefined} value
 * @return {!proto.message.Wrapper} returns this
*/
proto.message.Wrapper.prototype.setGameinit = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.message.Wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.message.Wrapper} returns this
 */
proto.message.Wrapper.prototype.clearGameinit = function() {
  return this.setGameinit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.message.Wrapper.prototype.hasGameinit = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional GameStart gameStart = 7;
 * @return {?proto.message.GameStart}
 */
proto.message.Wrapper.prototype.getGamestart = function() {
  return /** @type{?proto.message.GameStart} */ (
    jspb.Message.getWrapperField(this, proto.message.GameStart, 7));
};


/**
 * @param {?proto.message.GameStart|undefined} value
 * @return {!proto.message.Wrapper} returns this
*/
proto.message.Wrapper.prototype.setGamestart = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.message.Wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.message.Wrapper} returns this
 */
proto.message.Wrapper.prototype.clearGamestart = function() {
  return this.setGamestart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.message.Wrapper.prototype.hasGamestart = function() {
  return jspb.Message.getField(this, 7) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.GameInit.prototype.toObject = function(opt_includeInstance) {
  return proto.message.GameInit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.GameInit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.GameInit.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.GameInit}
 */
proto.message.GameInit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.GameInit;
  return proto.message.GameInit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.GameInit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.GameInit}
 */
proto.message.GameInit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.GameInit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.GameInit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.GameInit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.GameInit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.message.GameInit.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.message.GameInit} returns this
 */
proto.message.GameInit.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.ChangeDir.prototype.toObject = function(opt_includeInstance) {
  return proto.message.ChangeDir.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.ChangeDir} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.ChangeDir.toObject = function(includeInstance, msg) {
  var f, obj = {
angle: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
ismoved: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.ChangeDir}
 */
proto.message.ChangeDir.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.ChangeDir;
  return proto.message.ChangeDir.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.ChangeDir} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.ChangeDir}
 */
proto.message.ChangeDir.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAngle(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsmoved(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.ChangeDir.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.ChangeDir.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.ChangeDir} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.ChangeDir.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAngle();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getIsmoved();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional float angle = 1;
 * @return {number}
 */
proto.message.ChangeDir.prototype.getAngle = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.message.ChangeDir} returns this
 */
proto.message.ChangeDir.prototype.setAngle = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional bool isMoved = 2;
 * @return {boolean}
 */
proto.message.ChangeDir.prototype.getIsmoved = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.message.ChangeDir} returns this
 */
proto.message.ChangeDir.prototype.setIsmoved = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.message.GameState.repeatedFields_ = [1,2,3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.GameState.prototype.toObject = function(opt_includeInstance) {
  return proto.message.GameState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.GameState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.GameState.toObject = function(includeInstance, msg) {
  var f, obj = {
playerstateList: jspb.Message.toObjectList(msg.getPlayerstateList(),
    proto.message.PlayerState.toObject, includeInstance),
bulletstateList: jspb.Message.toObjectList(msg.getBulletstateList(),
    proto.message.BulletState.toObject, includeInstance),
healpackstateList: jspb.Message.toObjectList(msg.getHealpackstateList(),
    proto.message.HealPackState.toObject, includeInstance),
magicitemstateList: jspb.Message.toObjectList(msg.getMagicitemstateList(),
    proto.message.MagicItemState.toObject, includeInstance),
playerdeadstateList: jspb.Message.toObjectList(msg.getPlayerdeadstateList(),
    proto.message.PlayerDeadState.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.GameState}
 */
proto.message.GameState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.GameState;
  return proto.message.GameState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.GameState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.GameState}
 */
proto.message.GameState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.message.PlayerState;
      reader.readMessage(value,proto.message.PlayerState.deserializeBinaryFromReader);
      msg.addPlayerstate(value);
      break;
    case 2:
      var value = new proto.message.BulletState;
      reader.readMessage(value,proto.message.BulletState.deserializeBinaryFromReader);
      msg.addBulletstate(value);
      break;
    case 3:
      var value = new proto.message.HealPackState;
      reader.readMessage(value,proto.message.HealPackState.deserializeBinaryFromReader);
      msg.addHealpackstate(value);
      break;
    case 4:
      var value = new proto.message.MagicItemState;
      reader.readMessage(value,proto.message.MagicItemState.deserializeBinaryFromReader);
      msg.addMagicitemstate(value);
      break;
    case 5:
      var value = new proto.message.PlayerDeadState;
      reader.readMessage(value,proto.message.PlayerDeadState.deserializeBinaryFromReader);
      msg.addPlayerdeadstate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.GameState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.GameState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.GameState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.GameState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerstateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.message.PlayerState.serializeBinaryToWriter
    );
  }
  f = message.getBulletstateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.message.BulletState.serializeBinaryToWriter
    );
  }
  f = message.getHealpackstateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.message.HealPackState.serializeBinaryToWriter
    );
  }
  f = message.getMagicitemstateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.message.MagicItemState.serializeBinaryToWriter
    );
  }
  f = message.getPlayerdeadstateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.message.PlayerDeadState.serializeBinaryToWriter
    );
  }
};


/**
 * repeated PlayerState playerState = 1;
 * @return {!Array<!proto.message.PlayerState>}
 */
proto.message.GameState.prototype.getPlayerstateList = function() {
  return /** @type{!Array<!proto.message.PlayerState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.message.PlayerState, 1));
};


/**
 * @param {!Array<!proto.message.PlayerState>} value
 * @return {!proto.message.GameState} returns this
*/
proto.message.GameState.prototype.setPlayerstateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.message.PlayerState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.message.PlayerState}
 */
proto.message.GameState.prototype.addPlayerstate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.message.PlayerState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.message.GameState} returns this
 */
proto.message.GameState.prototype.clearPlayerstateList = function() {
  return this.setPlayerstateList([]);
};


/**
 * repeated BulletState bulletState = 2;
 * @return {!Array<!proto.message.BulletState>}
 */
proto.message.GameState.prototype.getBulletstateList = function() {
  return /** @type{!Array<!proto.message.BulletState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.message.BulletState, 2));
};


/**
 * @param {!Array<!proto.message.BulletState>} value
 * @return {!proto.message.GameState} returns this
*/
proto.message.GameState.prototype.setBulletstateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.message.BulletState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.message.BulletState}
 */
proto.message.GameState.prototype.addBulletstate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.message.BulletState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.message.GameState} returns this
 */
proto.message.GameState.prototype.clearBulletstateList = function() {
  return this.setBulletstateList([]);
};


/**
 * repeated HealPackState healPackState = 3;
 * @return {!Array<!proto.message.HealPackState>}
 */
proto.message.GameState.prototype.getHealpackstateList = function() {
  return /** @type{!Array<!proto.message.HealPackState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.message.HealPackState, 3));
};


/**
 * @param {!Array<!proto.message.HealPackState>} value
 * @return {!proto.message.GameState} returns this
*/
proto.message.GameState.prototype.setHealpackstateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.message.HealPackState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.message.HealPackState}
 */
proto.message.GameState.prototype.addHealpackstate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.message.HealPackState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.message.GameState} returns this
 */
proto.message.GameState.prototype.clearHealpackstateList = function() {
  return this.setHealpackstateList([]);
};


/**
 * repeated MagicItemState magicItemState = 4;
 * @return {!Array<!proto.message.MagicItemState>}
 */
proto.message.GameState.prototype.getMagicitemstateList = function() {
  return /** @type{!Array<!proto.message.MagicItemState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.message.MagicItemState, 4));
};


/**
 * @param {!Array<!proto.message.MagicItemState>} value
 * @return {!proto.message.GameState} returns this
*/
proto.message.GameState.prototype.setMagicitemstateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.message.MagicItemState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.message.MagicItemState}
 */
proto.message.GameState.prototype.addMagicitemstate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.message.MagicItemState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.message.GameState} returns this
 */
proto.message.GameState.prototype.clearMagicitemstateList = function() {
  return this.setMagicitemstateList([]);
};


/**
 * repeated PlayerDeadState playerDeadState = 5;
 * @return {!Array<!proto.message.PlayerDeadState>}
 */
proto.message.GameState.prototype.getPlayerdeadstateList = function() {
  return /** @type{!Array<!proto.message.PlayerDeadState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.message.PlayerDeadState, 5));
};


/**
 * @param {!Array<!proto.message.PlayerDeadState>} value
 * @return {!proto.message.GameState} returns this
*/
proto.message.GameState.prototype.setPlayerdeadstateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.message.PlayerDeadState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.message.PlayerDeadState}
 */
proto.message.GameState.prototype.addPlayerdeadstate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.message.PlayerDeadState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.message.GameState} returns this
 */
proto.message.GameState.prototype.clearPlayerdeadstateList = function() {
  return this.setPlayerdeadstateList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.PlayerState.prototype.toObject = function(opt_includeInstance) {
  return proto.message.PlayerState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.PlayerState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.PlayerState.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
x: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
y: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
health: jspb.Message.getFieldWithDefault(msg, 4, 0),
magictype: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.PlayerState}
 */
proto.message.PlayerState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.PlayerState;
  return proto.message.PlayerState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.PlayerState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.PlayerState}
 */
proto.message.PlayerState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHealth(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMagictype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.PlayerState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.PlayerState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.PlayerState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.PlayerState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getHealth();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getMagictype();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.message.PlayerState.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.message.PlayerState} returns this
 */
proto.message.PlayerState.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float x = 2;
 * @return {number}
 */
proto.message.PlayerState.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.message.PlayerState} returns this
 */
proto.message.PlayerState.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float y = 3;
 * @return {number}
 */
proto.message.PlayerState.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.message.PlayerState} returns this
 */
proto.message.PlayerState.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional int32 health = 4;
 * @return {number}
 */
proto.message.PlayerState.prototype.getHealth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.message.PlayerState} returns this
 */
proto.message.PlayerState.prototype.setHealth = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 magicType = 5;
 * @return {number}
 */
proto.message.PlayerState.prototype.getMagictype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.message.PlayerState} returns this
 */
proto.message.PlayerState.prototype.setMagictype = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.CreateBullet.prototype.toObject = function(opt_includeInstance) {
  return proto.message.CreateBullet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.CreateBullet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.CreateBullet.toObject = function(includeInstance, msg) {
  var f, obj = {
angle: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.CreateBullet}
 */
proto.message.CreateBullet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.CreateBullet;
  return proto.message.CreateBullet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.CreateBullet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.CreateBullet}
 */
proto.message.CreateBullet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAngle(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.CreateBullet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.CreateBullet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.CreateBullet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.CreateBullet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAngle();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
};


/**
 * optional float angle = 1;
 * @return {number}
 */
proto.message.CreateBullet.prototype.getAngle = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.message.CreateBullet} returns this
 */
proto.message.CreateBullet.prototype.setAngle = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.BulletState.prototype.toObject = function(opt_includeInstance) {
  return proto.message.BulletState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.BulletState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.BulletState.toObject = function(includeInstance, msg) {
  var f, obj = {
bulletid: jspb.Message.getFieldWithDefault(msg, 1, ""),
bullettype: jspb.Message.getFieldWithDefault(msg, 2, 0),
x: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
y: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.BulletState}
 */
proto.message.BulletState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.BulletState;
  return proto.message.BulletState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.BulletState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.BulletState}
 */
proto.message.BulletState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBulletid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBullettype(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.BulletState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.BulletState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.BulletState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.BulletState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBulletid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBullettype();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional string bulletId = 1;
 * @return {string}
 */
proto.message.BulletState.prototype.getBulletid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.message.BulletState} returns this
 */
proto.message.BulletState.prototype.setBulletid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 bulletType = 2;
 * @return {number}
 */
proto.message.BulletState.prototype.getBullettype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.message.BulletState} returns this
 */
proto.message.BulletState.prototype.setBullettype = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional float x = 3;
 * @return {number}
 */
proto.message.BulletState.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.message.BulletState} returns this
 */
proto.message.BulletState.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float y = 4;
 * @return {number}
 */
proto.message.BulletState.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.message.BulletState} returns this
 */
proto.message.BulletState.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.GameCount.prototype.toObject = function(opt_includeInstance) {
  return proto.message.GameCount.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.GameCount} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.GameCount.toObject = function(includeInstance, msg) {
  var f, obj = {
count: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.GameCount}
 */
proto.message.GameCount.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.GameCount;
  return proto.message.GameCount.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.GameCount} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.GameCount}
 */
proto.message.GameCount.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.GameCount.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.GameCount.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.GameCount} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.GameCount.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 count = 1;
 * @return {number}
 */
proto.message.GameCount.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.message.GameCount} returns this
 */
proto.message.GameCount.prototype.setCount = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.DoDash.prototype.toObject = function(opt_includeInstance) {
  return proto.message.DoDash.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.DoDash} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.DoDash.toObject = function(includeInstance, msg) {
  var f, obj = {
dash: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.DoDash}
 */
proto.message.DoDash.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.DoDash;
  return proto.message.DoDash.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.DoDash} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.DoDash}
 */
proto.message.DoDash.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDash(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.DoDash.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.DoDash.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.DoDash} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.DoDash.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDash();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool dash = 1;
 * @return {boolean}
 */
proto.message.DoDash.prototype.getDash = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.message.DoDash} returns this
 */
proto.message.DoDash.prototype.setDash = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.GameStart.prototype.toObject = function(opt_includeInstance) {
  return proto.message.GameStart.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.GameStart} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.GameStart.toObject = function(includeInstance, msg) {
  var f, obj = {
maplength: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.GameStart}
 */
proto.message.GameStart.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.GameStart;
  return proto.message.GameStart.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.GameStart} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.GameStart}
 */
proto.message.GameStart.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaplength(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.GameStart.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.GameStart.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.GameStart} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.GameStart.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaplength();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 mapLength = 1;
 * @return {number}
 */
proto.message.GameStart.prototype.getMaplength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.message.GameStart} returns this
 */
proto.message.GameStart.prototype.setMaplength = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.HealPackState.prototype.toObject = function(opt_includeInstance) {
  return proto.message.HealPackState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.HealPackState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.HealPackState.toObject = function(includeInstance, msg) {
  var f, obj = {
itemid: jspb.Message.getFieldWithDefault(msg, 1, ""),
x: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
y: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.HealPackState}
 */
proto.message.HealPackState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.HealPackState;
  return proto.message.HealPackState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.HealPackState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.HealPackState}
 */
proto.message.HealPackState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setItemid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.HealPackState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.HealPackState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.HealPackState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.HealPackState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
};


/**
 * optional string itemId = 1;
 * @return {string}
 */
proto.message.HealPackState.prototype.getItemid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.message.HealPackState} returns this
 */
proto.message.HealPackState.prototype.setItemid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float x = 2;
 * @return {number}
 */
proto.message.HealPackState.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.message.HealPackState} returns this
 */
proto.message.HealPackState.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float y = 3;
 * @return {number}
 */
proto.message.HealPackState.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.message.HealPackState} returns this
 */
proto.message.HealPackState.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.MagicItemState.prototype.toObject = function(opt_includeInstance) {
  return proto.message.MagicItemState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.MagicItemState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.MagicItemState.toObject = function(includeInstance, msg) {
  var f, obj = {
itemid: jspb.Message.getFieldWithDefault(msg, 1, ""),
magictype: jspb.Message.getFieldWithDefault(msg, 2, 0),
x: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
y: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.MagicItemState}
 */
proto.message.MagicItemState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.MagicItemState;
  return proto.message.MagicItemState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.MagicItemState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.MagicItemState}
 */
proto.message.MagicItemState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setItemid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMagictype(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.MagicItemState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.MagicItemState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.MagicItemState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.MagicItemState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMagictype();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional string itemId = 1;
 * @return {string}
 */
proto.message.MagicItemState.prototype.getItemid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.message.MagicItemState} returns this
 */
proto.message.MagicItemState.prototype.setItemid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 magicType = 2;
 * @return {number}
 */
proto.message.MagicItemState.prototype.getMagictype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.message.MagicItemState} returns this
 */
proto.message.MagicItemState.prototype.setMagictype = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional float x = 3;
 * @return {number}
 */
proto.message.MagicItemState.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.message.MagicItemState} returns this
 */
proto.message.MagicItemState.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float y = 4;
 * @return {number}
 */
proto.message.MagicItemState.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.message.MagicItemState} returns this
 */
proto.message.MagicItemState.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.message.PlayerDeadState.prototype.toObject = function(opt_includeInstance) {
  return proto.message.PlayerDeadState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.message.PlayerDeadState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.PlayerDeadState.toObject = function(includeInstance, msg) {
  var f, obj = {
killer: jspb.Message.getFieldWithDefault(msg, 1, ""),
dead: jspb.Message.getFieldWithDefault(msg, 2, ""),
dyingstatus: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.message.PlayerDeadState}
 */
proto.message.PlayerDeadState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.message.PlayerDeadState;
  return proto.message.PlayerDeadState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.message.PlayerDeadState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.message.PlayerDeadState}
 */
proto.message.PlayerDeadState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKiller(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDead(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDyingstatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.message.PlayerDeadState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.message.PlayerDeadState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.message.PlayerDeadState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.message.PlayerDeadState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKiller();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDead();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDyingstatus();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string killer = 1;
 * @return {string}
 */
proto.message.PlayerDeadState.prototype.getKiller = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.message.PlayerDeadState} returns this
 */
proto.message.PlayerDeadState.prototype.setKiller = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string dead = 2;
 * @return {string}
 */
proto.message.PlayerDeadState.prototype.getDead = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.message.PlayerDeadState} returns this
 */
proto.message.PlayerDeadState.prototype.setDead = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 dyingStatus = 3;
 * @return {number}
 */
proto.message.PlayerDeadState.prototype.getDyingstatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.message.PlayerDeadState} returns this
 */
proto.message.PlayerDeadState.prototype.setDyingstatus = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


goog.object.extend(exports, proto.message);
